# inherit from the proprietary version
#-include vendor/samsung/delos3geur/BoardConfigVendor.mk

#by wiki.cyanogenmod.org
TARGET_ARCH := arm
BOARD_KERNEL_CMDLINE := androidboot.hardware=qcom
BOARD_KERNEL_PAGESIZE := 4096
BOARD_BOOTIMAGE_PARTITION_SIZE := 12582912
BOARD_RECOVERYIMAGE_PARTITION_SIZE := 12582912
BOARD_SYSTEMIMAGE_PARTITION_SIZE := 1258291200
BOARD_USERDATAIMAGE_PARTITION_SIZE := 5573804032
BOARD_HAS_NO_SELECT_BUTTON := true
#BOARD_FORCE_RAMDISK_ADDRESS := 0x01300000
BOARD_MKBOOTIMG_ARGS := --ramdisk_offset 0x01300000 # 4.2+

TARGET_NO_BOOTLOADER := true
TARGET_BOARD_PLATFORM := msm7x27a # fixed
TARGET_CPU_ABI := armeabi-v7a
TARGET_CPU_ABI2 := armeabi
TARGET_ARCH_VARIANT := armv7-a-neon
TARGET_CPU_VARIANT := cortex-a5
TARGET_BOOTLOADER_BOARD_NAME := msm8625

# tweaking graphics
TARGET_SPECIFIC_HEADER_PATH := device/samsung/delos3geur/include
COMMON_GLOBAL_CFLAGS += -DQCOM_BSP -DQCOM_HARDWARE
#COMMON_GLOBAL_CFLAGS += -DQCOM_HARDWARE
COMMON_GLOBAL_CFLAGS += -DLPA_DEFAULT_BUFFER_SIZE=480

BOARD_USES_QCOM_HARDWARE := true
ARCH_ARM_HAVE_NEON := true
TARGET_USES_ION := true
TARGET_PROVIDES_LIBLIGHT := true
TARGET_GRALLOC_USES_ASHMEM := true

USE_OPENGL_RENDERER := true
TARGET_DOESNT_USE_FENCE_SYNC := true
BOARD_ADRENO_DECIDE_TEXTURE_TARGET := true
BOARD_EGL_NEEDS_LEGACY_FB := true
COMMON_GLOBAL_CFLAGS += -DQCOM_LEGACY_MMPARSE

COMMON_GLOBAL_CFLAGS += -DNO_TUNNEL_RECORDING
TARGET_USES_QCOM_BSP := true
TARGET_DISPLAY_USE_RETIRE_FENCE := true
BOARD_NEEDS_MEMORYHEAPPMEM := true
BOARD_USE_MHEAP_SCREENSHOT := true

BOARD_EGL_WORKAROUND_BUG_10194508 := true
HWUI_COMPILE_FOR_PERF := true
TARGET_NO_HW_VSYNC := true

ARCH_ARM_HAVE_TLS_REGISTER := true
TARGET_CORTEX_CACHE_LINE_32 := true
ARCH_ARM_HAVE_32_BYTE_CACHE_LINES := true
TARGET_USE_QCOM_BIONIC_OPTIMIZATION := true
TARGET_QCOM_MEDIA_VARIANT := legacy

TARGET_BOARD_PLATFORM_GPU := qcom-adreno203
BOARD_USES_ADRENO_200 := true

# Samsung has weird framebuffer
TARGET_NO_INITLOGO := true
DEVICE_RESOLUTION := 480x800
#BOARD_KERNEL_BASE := 0x00200000

# tweaking audio
TARGET_PROVIDES_LIBAUDIO := true
#BOARD_USES_AUDIO_LEGACY := false
# use weritos cm11 audio HAL without libaudcal
TARGET_HAS_QACT := false

# tweaking power
TARGET_POWERHAL_VARIANT :=

# tweaking RIL by weritos
BOARD_PROVIDES_LIBRIL := true
#BOARD_RIL_CLASS := ../../../device/samsung/delos3geur/ril/java_ril
COMMON_GLOBAL_CFLAGS += -DRIL_SUPPORTS_SEEK
COMMON_GLOBAL_CFLAGS += -DRIL_VARIANT_LEGACY 

# Wi-Fi by weritos
BOARD_WLAN_DEVICE := ath6kl
# moved to libhardware_legacy
#TARGET_CUSTOM_WIFI := device/samsung/delos3geur/wifi/wifi.c
WPA_SUPPLICANT_VERSION := VER_0_8_X
BOARD_WPA_SUPPLICANT_DRIVER := NL80211
WIFI_DRIVER_IFACE_NAME := "wlan0"
BOARD_WPA_SUPPLICANT_PRIVATE_LIB := lib_driver_cmd_ath6kl
BOARD_HOSTAPD_DRIVER := NL80211
BOARD_HOSTAPD_PRIVATE_LIB := lib_driver_cmd_ath6kl
WIFI_EXT_MODULE_NAME := "cfg80211"
WIFI_EXT_MODULE_PATH := "/system/lib/modules/cfg80211.ko"
WIFI_DRIVER_MODULE_AP_ARG := "suspend_mode=3 wow_mode=2 ath6kl_p2p=1 recovery_enable=1"
WIFI_DRIVER_MODULE_NAME := "ath6kl_sdio"
WIFI_DRIVER_MODULE_PATH := "/system/lib/modules/ath6kl_sdio.ko"
WIFI_DRIVER_MODULE_ARG := "suspend_mode=3 wow_mode=2 ath6kl_p2p=1 recovery_enable=1"
WIFI_DRIVER_FW_PATH_PARAM := "/data/misc/wifi/fwpath"

# GPS by weritos
#QCOM_GPS_PATH := hardware/qcom/gps
#TARGET_PROVIDES_GPS_LOC_API := true
BOARD_USES_QCOM_LIBRPC := true
BOARD_USES_QCOM_GPS := true
BOARD_VENDOR_QCOM_GPS_LOC_API_AMSS_VERSION := 50001
BOARD_VENDOR_QCOM_GPS_LOC_API_HARDWARE := $(TARGET_BOARD_PLATFORM) 

# partitions
#BOARD_VOLD_MAX_PARTITIONS := 32
BOARD_DATA_DEVICE := /dev/block/mmcblk0p24
BOARD_DATA_FILESYSTEM := ext4
BOARD_DATA_FILESYSTEM_OPTIONS := rw
BOARD_SYSTEM_DEVICE := /dev/block/mmcblk0p21
BOARD_SYSTEM_FILESYSTEM := ext4
BOARD_SYSTEM_FILESYSTEM_OPTIONS := rw
BOARD_CACHE_DEVICE := /dev/block/mmcblk0p22
BOARD_CACHE_FILESYSTEM := ext4
BOARD_CACHE_FILESYSTEM_OPTIONS := rw

BOARD_CACHEIMAGE_PARTITION_SIZE := 41943040
BOARD_FLASH_BLOCK_SIZE := 131072
BOARD_WANTS_EMMC_BOOT := true
BOARD_USE_LEGACY_UI := true
BOARD_EGL_CFG := device/samsung/delos3geur/config/egl.cfg

# maybe this will help?
#TARGET_USE_CUSTOM_LUN_FILE_PATH := /sys/devices/platform/msm_hsusb/gadget/lun0/file

TARGET_PREBUILT_KERNEL := device/samsung/delos3geur/kernel
# Inline kernel building
#TARGET_KERNEL_SOURCE := kernel/samsung/delos3geur
#TARGET_KERNEL_CONFIG := cm10_delos3geur_defconfig

# Use this flag if the board has a ext4 partition larger than 2gb
BOARD_HAS_LARGE_FILESYSTEM := true
USE_CAMERA_STUB := true
BOARD_HAVE_BLUETOOTH := false
BOARD_HAVE_QCOM_FM := false

#BOARD_USE_LEGACY_TOUCHSCREEN := true

DISABLE_DEXPREOPT := true

#TARGET_NO_RECOVERY := true
TARGET_NO_RADIOIMAGE := true
#TARGET_NO_BOOTIMAGE := true